export const RAW_LEGACY_URLS = `https://truyenchu.vn/40-ngay-ket-hon
https://truyenchu.vn/anh-nang-ban-mai-o-di-gioi
https://truyenchu.vn/anh-se-noi-yeu-em-o-thien-duong
https://truyenchu.vn/apple-app-site-association
https://truyenchu.vn/ba-vuong-thuong/chuong-3
https://truyenchu.vn/bao-quan-doc-sung
https://truyenchu.vn/bat-diet-kiem-quan/chuong-3
https://truyenchu.vn/bat-phu-vinh-quang-bat-phu-em
https://truyenchu.vn/bat-tu-mot-phan-hai
https://truyenchu.vn/be-con-lam-vo-anh-nhe
https://truyenchu.vn/ben-nhau-tron-doi
https://truyenchu.vn/cam-thu-nuoi-nhot-co-gai-nho
https://truyenchu.vn/canh-sat-dai-ty-va-co-giao/chuong-72
https://truyenchu.vn/chi-dau-lai-la-vo-yeu
https://truyenchu.vn/chi-ton-dong-thuat-su
https://truyenchu.vn/cho-anh-den-cung-gio
https://truyenchu.vn/chu-a-rot-cuoc-anh-nghi-gi-vay
https://truyenchu.vn/chu-a-rot-cuoc-anh-nghi-gi-vay/chuong-10
https://truyenchu.vn/chu-re-cua-toi-bo-tron-roi
https://truyenchu.vn/co-ay-yeu-tien-hon-toi
https://truyenchu.vn/co-vo-nho-trong-sinh-cua-bo-truong
https://truyenchu.vn/coi-sach-giai-tri
https://truyenchu.vn/cuoc-dinh-menh-thu-vi
https://truyenchu.vn/cuoc-hon-nhan-dai-lau
https://truyenchu.vn/cuu-thien
https://truyenchu.vn/dai-lao-vi-ta-than-hon-dien-dao-xuyen-nhanh/chuong-22
https://truyenchu.vn/dai-vuong-tha-mang
https://truyenchu.vn/danh-sach/dam-my-h-van
https://truyenchu.vn/danh-sach/dam-my-sac
https://truyenchu.vn/danh-sach/kiem-hiep-hay
https://truyenchu.vn/danh-sach/ngon-tinh-nguoc
https://truyenchu.vn/danh-sach/tien-hiep-hay
https://truyenchu.vn/danh-sach/truyen-convert
https://truyenchu.vn/danh-sach/truyen-dich
https://truyenchu.vn/danh-sach/truyen-hot
https://truyenchu.vn/danh-sach/truyen-moi
https://truyenchu.vn/dao-quy-di-tien
https://truyenchu.vn/dau-la-dai-luc-review
https://truyenchu.vn/dau-pha-thuong-khung
https://truyenchu.vn/day-xich-tinh-yeu
https://truyenchu.vn/de-con-co-cai-duoi-mau-xanh
https://truyenchu.vn/den-trang/chuong-43
https://truyenchu.vn/dien-vien-mat-sung-dien-vien-ngot-sung
https://truyenchu.vn/do-thi-co-tien-y
https://truyenchu.vn/do-thi-toi-cuong-tien-de
https://truyenchu.vn/do-thi-y-tien
https://truyenchu.vn/doat-dau-nguoi-trong-game-escape/chuong-78
https://truyenchu.vn/dom-dom-mua-ha/chuong-1
https://truyenchu.vn/dong-nhan-gio-am-khong-bang-anh-tham-tinh
https://truyenchu.vn/dong-nhan-gio-am-khong-bang-anh-tham-tinh/chuong-9
https://truyenchu.vn/em-co-quyen-duy-tri-tram-mac
https://truyenchu.vn/hay-khoc-va-cau-nguyen-di
https://truyenchu.vn/he-thong-xuyen-nhanh-cai-tao-thang-nam
https://truyenchu.vn/hon-de-giac-tinh/chuong-1
https://truyenchu.vn/hon-nhan-khong-tinh-yeu
https://truyenchu.vn/huyen-gioi-chi-mon
https://truyenchu.vn/ket-hon-ma-thoi
https://truyenchu.vn/khi-benh-kieu-hac-hoa
https://truyenchu.vn/khong-ai-yeu-em
https://truyenchu.vn/kiem-linh
https://truyenchu.vn/kumo-desu-ga-nani-ka
https://truyenchu.vn/lao-dai-phu-nhan-duoi-toi-roi/chuong-500
https://truyenchu.vn/linh-kiem-ton
https://truyenchu.vn/linh-vu-thien-ha
https://truyenchu.vn/luc-thieu-chi-yeu-co-vo-ngoc
https://truyenchu.vn/mang-theo-chung-cu-xuyen-toi-thap-nien-50
https://truyenchu.vn/mi-tuong-quan
https://truyenchu.vn/mieng-doc-thanh-doi
https://truyenchu.vn/minh-chu
https://truyenchu.vn/muc-than-ky
https://truyenchu.vn/ngau-nhien-khai-thien-nhan-tao-kich-thau/chuong-2
https://truyenchu.vn/ngay-thang-trac-tro
https://truyenchu.vn/nghich-tap-sung-nhanh-con-kip/chuong-1
https://truyenchu.vn/nghich-thien-ta-than
https://truyenchu.vn/nguoi-nhat-thi-o-conan
https://truyenchu.vn/nha-ta-de-nu-sieu-hung-tan
https://truyenchu.vn/nhan-qua-luu-ngan
https://truyenchu.vn/nhiep-chinh-vuong-benh-kieu-duoc-sung-ai
https://truyenchu.vn/non-noi-non-xanh
https://truyenchu.vn/nu-nhan-cua-ta-nguoi-khong-choc-noi
https://truyenchu.vn/on-nhu-yeu-nguoi
https://truyenchu.vn/phao-hoi-nguyen-phoi-nghich-tap-so-tay
https://truyenchu.vn/phao-hoi-nguyen-phoi-nghich-tap-so-tay/chuong-20
https://truyenchu.vn/phu-cam
https://truyenchu.vn/phu-hoang
https://truyenchu.vn/phuong-nghich-cuu-thien/chuong-152
https://truyenchu.vn/quan-hon-keo-dai-co-thieu-sung-the-vo-do-hay-nhat-2013
https://truyenchu.vn/quy-dao-chi-chu
https://truyenchu.vn/quyen-ru
https://truyenchu.vn/soi-to-do
https://truyenchu.vn/song-bang-tan-the-ta-tru-hang-chuc-ty-vat-tu
https://truyenchu.vn/song-trinh-mai-mai-mot-tinh-yeu
https://truyenchu.vn/su-phu-ta-sieu-cuong-lai-qua-phan-vung-vang/chuong-267
https://truyenchu.vn/ta-my-nu-nha-tro
https://truyenchu.vn/tac-gia/akay-hau
https://truyenchu.vn/tac-gia/ban-tiet-bach-thai
https://truyenchu.vn/tac-gia/bat-chi-thi-khoa-thai
https://truyenchu.vn/tac-gia/co
https://truyenchu.vn/tac-gia/diep-phi-da
https://truyenchu.vn/tac-gia/dong-thien-dich-lieu-diep
https://truyenchu.vn/tac-gia/duoc-thien-sau
https://truyenchu.vn/tac-gia/erly
https://truyenchu.vn/tac-gia/gia-oan-chuc
https://truyenchu.vn/tac-gia/hac-am-sam-lam
https://truyenchu.vn/tac-gia/hoai-phi-van-van
https://truyenchu.vn/tac-gia/hong-can-to-tuu
https://truyenchu.vn/tac-gia/huynh-thien-ky
https://truyenchu.vn/tac-gia/j-than
https://truyenchu.vn/tac-gia/kim-hoa
https://truyenchu.vn/tac-gia/lac-thien-thien
https://truyenchu.vn/tac-gia/lam-lac-chu
https://truyenchu.vn/tac-gia/loan
https://truyenchu.vn/tac-gia/luc-nguyet-hao-tuyet
https://truyenchu.vn/tac-gia/luc-nhu-hoa-thuong
https://truyenchu.vn/tac-gia/mac-lam-hue
https://truyenchu.vn/tac-gia/mac-linh
https://truyenchu.vn/tac-gia/man-tay
https://truyenchu.vn/tac-gia/mo-nghia
https://truyenchu.vn/tac-gia/moc-li
https://truyenchu.vn/tac-gia/nga-cat-tay-hong-thi
https://truyenchu.vn/tac-gia/nghich-thuong-thien
https://truyenchu.vn/tac-gia/nguyen-bang-tram
https://truyenchu.vn/tac-gia/nguyet-xuat-van
https://truyenchu.vn/tac-gia/nhat-lo-phien-hoa
https://truyenchu.vn/tac-gia/oa-nguu-cuong-bon
https://truyenchu.vn/tac-gia/phi-yen
https://truyenchu.vn/tac-gia/quan-quan-huu-yeu
https://truyenchu.vn/tac-gia/sau-bat-lieu
https://truyenchu.vn/tac-gia/ta-la-lao-ngu
https://truyenchu.vn/tac-gia/tac-mi-thu-nhan
https://truyenchu.vn/tac-gia/thanh-tu
https://truyenchu.vn/tac-gia/thoi-tinh-thao
https://truyenchu.vn/tac-gia/thu-ngu
https://truyenchu.vn/tac-gia/tieu-that-gia
https://truyenchu.vn/tac-gia/tuyet-nguyen-u-linh
https://truyenchu.vn/tac-gia/van-thien-khong
https://truyenchu.vn/tac-gia/yeu-da
https://truyenchu.vn/tai-sinh-chi-tu
https://truyenchu.vn/tam-phuc
https://truyenchu.vn/tam-quoc-bat-dau-thay-the-ton-sach-dai-kieu-mang-thai
https://truyenchu.vn/tan-the-ben-canh-tat-ca-deu-la-nu-zombie
https://truyenchu.vn/than-cap-sao-chep-thien-phu-he-thong
https://truyenchu.vn/thanh-vuong/chuong-3
https://truyenchu.vn/thap-nien-70-tieu-banh-bao-pk-me-ke/chuong-50
https://truyenchu.vn/thap-nien-80-dai-vien-tieu-tuc-phu
https://truyenchu.vn/thap-nien-80-nang-dau-dung-manh
https://truyenchu.vn/the-bai-mat-that
https://truyenchu.vn/the-loai/chieu-hon
https://truyenchu.vn/the-loai/cung-dau
https://truyenchu.vn/the-loai/dam-my
https://truyenchu.vn/the-loai/do-thi
https://truyenchu.vn/the-loai/duc-vong-chiem-huu
https://truyenchu.vn/the-loai/hai-huoc
https://truyenchu.vn/the-loai/huyen-huyen
https://truyenchu.vn/the-loai/kiem-hiep
https://truyenchu.vn/the-loai/kimetsu-no-yaiba
https://truyenchu.vn/the-loai/light-novel
https://truyenchu.vn/the-loai/linh-di
https://truyenchu.vn/the-loai/mat-the
https://truyenchu.vn/the-loai/pheromone
https://truyenchu.vn/the-loai/phuong-tay
https://truyenchu.vn/the-loai/quan-truong
https://truyenchu.vn/the-loai/sac
https://truyenchu.vn/the-loai/showbiz
https://truyenchu.vn/the-loai/treu-choc-lan-nhau
https://truyenchu.vn/the-loai/trinh-tham
https://truyenchu.vn/the-loai/trong-sinh
https://truyenchu.vn/the-loai/truyen-teen
https://truyenchu.vn/the-loai/vong-du
https://truyenchu.vn/the-loai/xuyen-khong
https://truyenchu.vn/the-loai/xuyen-nhanh
https://truyenchu.vn/thien-truong-dia-cuu-yeu
https://truyenchu.vn/thinh-can-ta-cung-tong-giam-cp
https://truyenchu.vn/thoi-o-sach-cam-duc-bac-si
https://truyenchu.vn/thuc-cot-nguy-tinh-vo-cu-dung-hong-chay
https://truyenchu.vn/thuoc-ngot
https://truyenchu.vn/tien-dao-ta-quan
https://truyenchu.vn/tien-vo-de-ton
https://truyenchu.vn/tien-vuong-tai-xuat
https://truyenchu.vn/tieu-dia-chu-huyet-huyet
https://truyenchu.vn/tinh-yeu-va-am-muu
https://truyenchu.vn/toan-tri-doc-gia-app
https://truyenchu.vn/toi-cuong-phan-phai-he-thong
https://truyenchu.vn/toi-duoc-thua-huong-mot-hanh-tinh-trong-trot/chuong-1
https://truyenchu.vn/tong-hop-truyen-ngan-thanh-guom-diet-quy
https://truyenchu.vn/tong-tai-anh-sai-roi-shu-yang
https://truyenchu.vn/trach-anh-qua-dang-yeu/chuong-76
https://truyenchu.vn/trong-sinh-hau-cung-sam-quan-ky/chuong-1
https://truyenchu.vn/tu-ky-tuc-mira-phu-nhan-nha-bat-dau-thuong-ngay/chuong-9
https://truyenchu.vn/tu-la-chien-than
https://truyenchu.vn/tu-than-chi-tien
https://truyenchu.vn/tuyet-the-chien-hon
https://truyenchu.vn/vinh-hang-thanh-vuong
https://truyenchu.vn/vo-cua-tong-tai-khong-de
https://truyenchu.vn/vo-nho-mat-tri-nho-cua-dai-ca-xa-hoi-den
https://truyenchu.vn/vu-mo
https://truyenchu.vn/vuong-phi-da-tai-da-nghe
https://truyenchu.vn/warriors
https://truyenchu.vn/xuyen-qua-kiem-tien-nuoi-phu-lang
https://truyenchu.vn/xuyen-qua-lam-thu-cung-cua-nhan-vat-phan-dien/chuong-9
https://truyenchu.vn/xuyen-thanh-nhu-nhuoc-nu-xung-tieu-bach-mieu
https://truyenchu.vn/yeu-chi-can-ta-va-nguoi-hieu-bao
https://truyenchu.vn/yeu-phai-to-tien` as const;
